language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
 - chmod +x gradlew

after_success:
 - .travis-scripts/deploy-artifacts.sh
 - .travis-scripts/push-javadoc-to-gh-pages.sh
