language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
 - chmod +x gradlew

after_success:
 - test "${TRAVIS_PULL_REQUEST}" == "false" && test “${TRAVIS_JDK_VERSION}” == “oraclejdk7″ && test "${TRAVIS_TAG}" != "" && ./gradlew publishSnapshotOrRelease
